# Generated by Django 4.1.3 on 2022-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='rollno',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
