# Generated by Django 4.1.3 on 2022-12-10 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0002_alter_newuser_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='rollno',
            field=models.CharField(max_length=7, unique=True, verbose_name='Roll Number'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_time', models.DateTimeField()),
                ('content', models.TextField()),
                ('comment', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
