# Generated by Django 4.1.3 on 2022-12-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0003_alter_newuser_rollno_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post', max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
