# Generated by Django 4.1.3 on 2022-12-20 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0006_tokens_full_name_alter_post_post_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokens',
            name='full_name',
        ),
    ]
