# Generated by Django 4.1.3 on 2023-01-04 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0007_remove_tokens_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workplace', models.CharField(max_length=30, null=True)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('address_line_1', models.CharField(max_length=50, null=True)),
                ('address_line_2', models.CharField(max_length=50, null=True)),
                ('pin', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
