# Generated by Django 4.1.3 on 2023-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0011_event_alter_profile_dob_alter_profile_workplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
