# Generated by Django 4.1.3 on 2023-05-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0013_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
