# Generated by Django 4.1.3 on 2023-06-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mca', '0014_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=1, upload_to='posts'),
            preserve_default=False,
        ),
    ]
